/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

/**
 *
 * @author laisp
 */
public class Menu_Medico extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Medico
     */
    public Menu_Medico(int id) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jmCadExame = new javax.swing.JMenuItem();
        jmCadAgenda = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jmTabProntuario = new javax.swing.JMenuItem();
        jmTabExame = new javax.swing.JMenuItem();
        jmTabAgenda = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu3.setText("Acessos");

        jmCadExame.setText("Novo Exame");
        jmCadExame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadExameActionPerformed(evt);
            }
        });
        jMenu3.add(jmCadExame);

        jmCadAgenda.setText("Nova Agenda");
        jmCadAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadAgendaActionPerformed(evt);
            }
        });
        jMenu3.add(jmCadAgenda);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Alterações");

        jmTabProntuario.setText("Prontuario");
        jmTabProntuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmTabProntuarioActionPerformed(evt);
            }
        });
        jMenu4.add(jmTabProntuario);

        jmTabExame.setText("Exame");
        jmTabExame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmTabExameActionPerformed(evt);
            }
        });
        jMenu4.add(jmTabExame);

        jmTabAgenda.setText("Agenda");
        jmTabAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmTabAgendaActionPerformed(evt);
            }
        });
        jMenu4.add(jmTabAgenda);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 401, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 242, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmCadExameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadExameActionPerformed
       abrirCadExame();
    }//GEN-LAST:event_jmCadExameActionPerformed

    private void jmCadAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadAgendaActionPerformed
        abrirCadAgenda();
    }//GEN-LAST:event_jmCadAgendaActionPerformed

    private void jmTabProntuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmTabProntuarioActionPerformed
        abrirTabProntuario();
    }//GEN-LAST:event_jmTabProntuarioActionPerformed

    private void jmTabExameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmTabExameActionPerformed
        abrirTabExame();
    }//GEN-LAST:event_jmTabExameActionPerformed

    private void jmTabAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmTabAgendaActionPerformed
        abrirTabAgenda();
    }//GEN-LAST:event_jmTabAgendaActionPerformed

    private void abrirCadExame(){
        TelaCadExame tce = new TelaCadExame();
        tce.setVisible(true);
    }//fecha método
    
    private void abrirCadAgenda(){
        TelaCadAgenda tca = new TelaCadAgenda();
        tca.setVisible(true);
    }//fecha método
    
    private void abrirTabProntuario(){
        TelaTabProntuario ttp = new TelaTabProntuario();
        ttp.setVisible(true);
    }//fecha método
    
    private void abrirTabExame(){
        TelaTabExame tte = new TelaTabExame();
        tte.setVisible(true);
    }//fecha método
    
    private void abrirTabAgenda(){
        TelaTabAgenda tta = new TelaTabAgenda();
        tta.setVisible(true);
    }//fecha método
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Medico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Medico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Medico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Medico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Medico(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JMenuItem jmCadAgenda;
    private javax.swing.JMenuItem jmCadExame;
    private javax.swing.JMenuItem jmTabAgenda;
    private javax.swing.JMenuItem jmTabExame;
    private javax.swing.JMenuItem jmTabProntuario;
    // End of variables declaration//GEN-END:variables
}
