/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;


import controle.AgendaControle;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Agenda;


/**
 *
 * @author laisp
 */
public class TelaTabAgenda extends javax.swing.JFrame {

    DefaultTableModel dtm = new DefaultTableModel(
            new Object[][]{},
            new Object[]{"Idagenda", "Paciente", "Data e Hora", "Exame"});
    
    public TelaTabAgenda() {
        initComponents();
        preencherTabela();
        preencherAgenda();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfCodigo = new javax.swing.JTextField();
        jtfPaciente = new javax.swing.JTextField();
        jbAlaterar = new javax.swing.JButton();
        jbConfirmar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtDados = new javax.swing.JTable();
        jbAtualizar = new javax.swing.JButton();
        jlDia = new javax.swing.JLabel();
        jlMes = new javax.swing.JLabel();
        jlAno = new javax.swing.JLabel();
        jtfDia = new javax.swing.JTextField();
        jtfMes = new javax.swing.JTextField();
        jtfAno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtfHora = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtfMin = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        jLabel2.setText("Codigo:");

        jLabel3.setText("Paciente:");

        jtfCodigo.setEditable(false);
        jtfCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCodigoActionPerformed(evt);
            }
        });

        jtfPaciente.setEditable(false);
        jtfPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfPacienteActionPerformed(evt);
            }
        });

        jbAlaterar.setText("Alterar");
        jbAlaterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlaterarActionPerformed(evt);
            }
        });

        jbConfirmar.setText("Confirmar");
        jbConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConfirmarActionPerformed(evt);
            }
        });

        jtDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Paciente", "Data e Hora", "Exame"
            }
        ));
        jScrollPane1.setViewportView(jtDados);

        jbAtualizar.setText("Atualizar");
        jbAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAtualizarActionPerformed(evt);
            }
        });

        jlDia.setText("Data:");

        jlMes.setText("/");

        jlAno.setText("/");

        jtfDia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfDiaFocusLost(evt);
            }
        });
        jtfDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDiaActionPerformed(evt);
            }
        });

        jtfMes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfMesFocusLost(evt);
            }
        });

        jtfAno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfAnoFocusLost(evt);
            }
        });
        jtfAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfAnoActionPerformed(evt);
            }
        });

        jLabel5.setText("Hora:");

        jLabel6.setText(":");

        jLabel4.setText("Exame:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtfPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jbAlaterar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlDia)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtfDia, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jlMes)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfMes, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jlAno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfAno, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfHora, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jtfMin, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(jbConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDia)
                    .addComponent(jlMes)
                    .addComponent(jtfDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlAno)
                    .addComponent(jtfAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jtfMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jtfHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAlaterar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConfirmarActionPerformed
        confirmarAlteracao();
        limparTabela();
        limparCampos();
        preencherTabela();
    }//GEN-LAST:event_jbConfirmarActionPerformed

    private void jbAlaterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlaterarActionPerformed
        alterar();
    }//GEN-LAST:event_jbAlaterarActionPerformed

    private void jbAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAtualizarActionPerformed
        limparTabela();
        preencherTabela();
    }//GEN-LAST:event_jbAtualizarActionPerformed

    private void jtfPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPacienteActionPerformed
        
    }//GEN-LAST:event_jtfPacienteActionPerformed

    private void jtfCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCodigoActionPerformed
        if(jtfCodigo.getText().isEmpty()){
            jtfCodigo.setBackground(Color.red);
            
        }else{
            jtfCodigo.setBackground(Color.white);
           
        }//fecha else
    }//GEN-LAST:event_jtfCodigoActionPerformed

    private void jtfDiaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfDiaFocusLost
        if(jtfDia.getText().isEmpty()){
            jtfDia.setBackground(Color.red);

        }else{
            jtfDia.setBackground(Color.white);

        }//fecha else
    }//GEN-LAST:event_jtfDiaFocusLost

    private void jtfDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDiaActionPerformed

    private void jtfMesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfMesFocusLost
        if(jtfMes.getText().isEmpty()){
            jtfMes.setBackground(Color.red);

        }else{
            jtfMes.setBackground(Color.white);

        }//fecha else
    }//GEN-LAST:event_jtfMesFocusLost

    private void jtfAnoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfAnoFocusLost
        if(jtfAno.getText().isEmpty()){
            jtfAno.setBackground(Color.red);

        }else{
            jtfAno.setBackground(Color.white);

        }//fecha else
    }//GEN-LAST:event_jtfAnoFocusLost

    private void jtfAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfAnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfAnoActionPerformed

    private void preencherAgenda(){
        try {
            AgendaControle ac = new AgendaControle();
            
            ArrayList<String> ta = new ArrayList();
            
            ta = ac.preencherAgenda();
            for (int i = 0; i <ta.size(); i++){
                jComboBox1.addItem(ta.get(i));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                this, "Erro! " + e.getMessage());
        }
    }
    
    private void preencherTabela() {
        try {
            
            AgendaControle a = new AgendaControle();

            ArrayList<Agenda> age = new ArrayList<>();
            
            age = a.preencherTabela();
            dtm.setNumRows(0);
            for (int i = 0; i <age.size(); i++) {
                dtm.addRow(new Object[]{
                    String.valueOf(age.get(i).getid_Agenda()),
                    String.valueOf(age.get(i).getPaciente()),
                    String.valueOf(age.get(i).juntarDataTabela()),
                    String.valueOf(age.get(i).getexame())
                     
            });
            }//fecha for

            /* Adicionando o modelo de tabela 
             com os dados na tabela Agenda */
            jtDados.setModel(dtm);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Erro! " + e.getMessage());
        }//fecha catch
    }//fecha preencherTabela
    
    private void alterar() {
        Agenda a = new Agenda();
        int linha = jtDados.getSelectedRow();
            if(linha != -1) {
            jtfCodigo.setText((String)jtDados.getValueAt(linha, 0));
            jtfPaciente.setText((String)jtDados.getValueAt(linha, 1));
            a.Data((String)jtDados.getValueAt(linha, 2));
            jtfDia.setText(a.getDia());
            jtfMes.setText(a.getMes());
            jtfAno.setText(a.getAno());
            jtfHora.setText(a.gethora());
            jtfMin.setText(a.getmin());
            
            
          
            }else{
                JOptionPane.showMessageDialog(this, 
                        "Você não selecionou nenhuma linha!");
         }//fecha else
    }//fecha método
    
    private void limparCampos(){
         jtfCodigo.setText("");
        jtfPaciente.setText("");
        jtfDia.setText("");
        jtfMes.setText("");
        jtfAno.setText("");
        jtfHora.setText("");
        jtfMin.setText("");
        
    }
    
    private void limparTabela() {
      /* Para limpar a tabela temos que setar o número de
           linhas para zero no default table model */        
        dtm.setNumRows(0);
    }//fecha limparTabela
    
     private void confirmarAlteracao(){
        try {
            Agenda a = new Agenda();
            AgendaControle ac = new AgendaControle();
            
            a.setid_Agenda(Integer.parseInt(jtfCodigo.getText()));
            a.setExametipo(ac.procurarId(jComboBox1.getSelectedItem().toString()));
            a.setPaciente(jtfPaciente.getText());
            a.setAno(jtfAno.getText());
            a.setMes(jtfMes.getText());
            a.setDia(jtfDia.getText());
            a.sethora(jtfHora.getText());
            a.setmin(jtfMin.getText());
            
            ac.alterarAgenda(a.getid_Agenda(), a.getAno(), a.getMes(), a.getDia(), a.gethora(), a.getmin(),a.getExametipo());
                    
            JOptionPane.showMessageDialog(
                    this,
                    "Produto alterado com sucesso!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                    "erro! " + e.getMessage());
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaTabAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaTabAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaTabAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaTabAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaTabAgenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAlaterar;
    private javax.swing.JButton jbAtualizar;
    private javax.swing.JButton jbConfirmar;
    private javax.swing.JLabel jlAno;
    private javax.swing.JLabel jlDia;
    private javax.swing.JLabel jlMes;
    private javax.swing.JTable jtDados;
    private javax.swing.JTextField jtfAno;
    private javax.swing.JTextField jtfCodigo;
    private javax.swing.JTextField jtfDia;
    private javax.swing.JTextField jtfHora;
    private javax.swing.JTextField jtfMes;
    private javax.swing.JTextField jtfMin;
    private javax.swing.JTextField jtfPaciente;
    // End of variables declaration//GEN-END:variables
}
