
package visao;

import controle.Adm;
import java.awt.Color;
import java.io.FileWriter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.Pessoa;

/**
 *
 * @author laisp
 */
public class TelaCadPessoa extends javax.swing.JFrame {

    /**
     * Creates new form GUICadPaciente
     */
    public TelaCadPessoa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlNome = new javax.swing.JLabel();
        jtfNome = new javax.swing.JTextField();
        jlCartao = new javax.swing.JLabel();
        jtSus = new javax.swing.JTextField();
        jlEstadoCivil = new javax.swing.JLabel();
        jtfEstadoCivil = new javax.swing.JTextField();
        jlSexo = new javax.swing.JLabel();
        jtfSexo = new javax.swing.JTextField();
        jlCor = new javax.swing.JLabel();
        jtfEtnia = new javax.swing.JTextField();
        jlRg = new javax.swing.JLabel();
        jtfRg = new javax.swing.JTextField();
        jlNum = new javax.swing.JLabel();
        jtfNumero = new javax.swing.JTextField();
        jlEndereco = new javax.swing.JLabel();
        jtfEndereco = new javax.swing.JTextField();
        jlCep = new javax.swing.JLabel();
        jtfCep = new javax.swing.JTextField();
        jlCidade = new javax.swing.JLabel();
        jtfCidade = new javax.swing.JTextField();
        jlEstado = new javax.swing.JLabel();
        jtfEstado = new javax.swing.JTextField();
        jlTelefone = new javax.swing.JLabel();
        jtfTelefone = new javax.swing.JTextField();
        bntCadastrar = new javax.swing.JButton();
        bntLimpar = new javax.swing.JButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jlCartao1 = new javax.swing.JLabel();
        jlNome1 = new javax.swing.JLabel();
        jtfNome1 = new javax.swing.JTextField();
        jtfCartao1 = new javax.swing.JTextField();
        jlEstadoCivil1 = new javax.swing.JLabel();
        jlCor1 = new javax.swing.JLabel();
        jlSexo1 = new javax.swing.JLabel();
        jlRg1 = new javax.swing.JLabel();
        jlEndereco1 = new javax.swing.JLabel();
        jlNumero = new javax.swing.JLabel();
        jlCep1 = new javax.swing.JLabel();
        jlCidade1 = new javax.swing.JLabel();
        jlEstado1 = new javax.swing.JLabel();
        jtfRg1 = new javax.swing.JTextField();
        jtfEndereco1 = new javax.swing.JTextField();
        jtfNumero1 = new javax.swing.JTextField();
        jtfCep1 = new javax.swing.JTextField();
        jtfCidade1 = new javax.swing.JTextField();
        jtfEstado1 = new javax.swing.JTextField();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jbLimpar = new javax.swing.JButton();
        jtfCor1 = new javax.swing.JTextField();
        jtfEstadoCivil1 = new javax.swing.JTextField();
        jtfSexo1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jlTelefone1 = new javax.swing.JLabel();
        jtfTelefone1 = new javax.swing.JTextField();
        jbCadastrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        jlCartao2 = new javax.swing.JLabel();
        jlNome2 = new javax.swing.JLabel();
        jtfNome2 = new javax.swing.JTextField();
        jtfCartao2 = new javax.swing.JTextField();
        jlEstadoCivil2 = new javax.swing.JLabel();
        jlCor2 = new javax.swing.JLabel();
        jlSexo2 = new javax.swing.JLabel();
        jlRg2 = new javax.swing.JLabel();
        jlEndereco2 = new javax.swing.JLabel();
        jlNumero1 = new javax.swing.JLabel();
        jlCep2 = new javax.swing.JLabel();
        jlCidade2 = new javax.swing.JLabel();
        jlEstado2 = new javax.swing.JLabel();
        jtfRg2 = new javax.swing.JTextField();
        jtfEndereco2 = new javax.swing.JTextField();
        jtfNumero2 = new javax.swing.JTextField();
        jtfCep2 = new javax.swing.JTextField();
        jtfCidade2 = new javax.swing.JTextField();
        jtfEstado2 = new javax.swing.JTextField();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jbLimpar1 = new javax.swing.JButton();
        jtfCor2 = new javax.swing.JTextField();
        jtfEstadoCivil2 = new javax.swing.JTextField();
        jtfSexo2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jlTelefone2 = new javax.swing.JLabel();
        jtfTelefone2 = new javax.swing.JTextField();
        jbCadastrar1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jtfTpo = new javax.swing.JTextField();

        jlNome.setText("Nome:");

        jtfNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNomeActionPerformed(evt);
            }
        });

        jlCartao.setText("Cartão Sus:");

        jtSus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtSusActionPerformed(evt);
            }
        });

        jlEstadoCivil.setText("Estado Civil (C = Casado, S = Solteiro):");

        jtfEstadoCivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfEstadoCivilActionPerformed(evt);
            }
        });

        jlSexo.setText("Sexo (F = Feminino, M = Masculino):");

        jtfSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfSexoActionPerformed(evt);
            }
        });

        jlCor.setText("Etnia:");

        jtfEtnia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfEtniaActionPerformed(evt);
            }
        });

        jlRg.setText("RG:");

        jtfRg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfRgActionPerformed(evt);
            }
        });

        jlNum.setText("Número:");

        jtfNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNumeroActionPerformed(evt);
            }
        });

        jlEndereco.setText("Endereco:");

        jtfEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfEnderecoActionPerformed(evt);
            }
        });

        jlCep.setText("CEP:");

        jtfCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCepActionPerformed(evt);
            }
        });

        jlCidade.setText("Cidade:");

        jtfCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCidadeActionPerformed(evt);
            }
        });

        jlEstado.setText("Estado:");

        jtfEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfEstadoActionPerformed(evt);
            }
        });

        jlTelefone.setText("Telefone:");

        jtfTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfTelefoneActionPerformed(evt);
            }
        });

        bntCadastrar.setText("CADASTRAR");
        bntCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntCadastrarActionPerformed(evt);
            }
        });

        bntLimpar.setText("LIMPAR");
        bntLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntLimparActionPerformed(evt);
            }
        });

        jInternalFrame1.setClosable(true);
        jInternalFrame1.setIconifiable(true);
        jInternalFrame1.setTitle("Novo Paciente");

        jlCartao1.setText("Cartão");

        jlNome1.setText("Nome");

        jtfNome1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfNome1FocusLost(evt);
            }
        });
        jtfNome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNome1ActionPerformed(evt);
            }
        });

        jtfCartao1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfCartao1FocusLost(evt);
            }
        });

        jlEstadoCivil1.setText("Estado Civil");

        jlCor1.setText("Cor");

        jlSexo1.setText("Sexo");

        jlRg1.setText("Rg");

        jlEndereco1.setText("Endereço");

        jlNumero.setText("Nº");

        jlCep1.setText("Cep");

        jlCidade1.setText("Cidade");

        jlEstado1.setText("Estado");

        jtfRg1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfRg1FocusLost(evt);
            }
        });

        jtfEndereco1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfEndereco1FocusLost(evt);
            }
        });

        jtfNumero1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfNumero1FocusLost(evt);
            }
        });

        jtfCep1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfCep1FocusLost(evt);
            }
        });

        jtfCidade1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfCidade1FocusLost(evt);
            }
        });

        jtfEstado1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfEstado1FocusLost(evt);
            }
        });

        jbLimpar.setText("Limpar");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        jLayeredPane2.setLayer(jbLimpar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 82, Short.MAX_VALUE))
        );

        jtfCor1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfCor1FocusLost(evt);
            }
        });

        jtfEstadoCivil1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfEstadoCivil1FocusLost(evt);
            }
        });

        jtfSexo1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfSexo1FocusLost(evt);
            }
        });
        jtfSexo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfSexo1ActionPerformed(evt);
            }
        });

        jlTelefone1.setText("Telefone");

        jtfTelefone1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfTelefone1FocusLost(evt);
            }
        });

        jbCadastrar.setText("Cadastrar");
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(jbCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLayeredPane2)
                        .addContainerGap())
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                        .addComponent(jlNome1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtfNome1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jlCartao1))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jInternalFrame1Layout.createSequentialGroup()
                                        .addComponent(jlEstadoCivil1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jtfEstadoCivil1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jlSexo1)))
                                .addGap(18, 18, 18)
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfCartao1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfSexo1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                        .addComponent(jlNumero)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtfNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addComponent(jlEndereco1))
                                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                        .addComponent(jlCor1)
                                        .addGap(35, 35, 35)
                                        .addComponent(jtfCor1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfEndereco1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(jlRg1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jtfRg1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jlCep1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfCep1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jlCidade1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfCidade1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(jlEstado1)
                                .addGap(18, 18, 18)
                                .addComponent(jtfEstado1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(jlTelefone1)
                                .addGap(18, 18, 18)
                                .addComponent(jtfTelefone1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(23, 23, 23))))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlNome1)
                            .addComponent(jlCartao1)
                            .addComponent(jtfNome1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfCartao1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlEstadoCivil1)
                            .addComponent(jlSexo1)
                            .addComponent(jtfEstadoCivil1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfSexo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfRg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlRg1))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlEndereco1)
                            .addComponent(jtfEndereco1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfCor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlCor1))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlNumero)
                            .addComponent(jtfNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlCep1)
                            .addComponent(jlCidade1)
                            .addComponent(jtfCep1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfCidade1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlEstado1)
                            .addComponent(jtfEstado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlTelefone1)
                            .addComponent(jtfTelefone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jInternalFrame2.setClosable(true);
        jInternalFrame2.setIconifiable(true);
        jInternalFrame2.setTitle("Novo Paciente");

        jlCartao2.setText("Cartão");

        jlNome2.setText("Nome");

        jtfNome2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfNome2FocusLost(evt);
            }
        });
        jtfNome2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNome2ActionPerformed(evt);
            }
        });

        jtfCartao2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfCartao2FocusLost(evt);
            }
        });

        jlEstadoCivil2.setText("Estado Civil");

        jlCor2.setText("Cor");

        jlSexo2.setText("Sexo");

        jlRg2.setText("Rg");

        jlEndereco2.setText("Endereço");

        jlNumero1.setText("Nº");

        jlCep2.setText("Cep");

        jlCidade2.setText("Cidade");

        jlEstado2.setText("Estado");

        jtfRg2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfRg2FocusLost(evt);
            }
        });

        jtfEndereco2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfEndereco2FocusLost(evt);
            }
        });

        jtfNumero2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfNumero2FocusLost(evt);
            }
        });

        jtfCep2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfCep2FocusLost(evt);
            }
        });

        jtfCidade2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfCidade2FocusLost(evt);
            }
        });

        jtfEstado2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfEstado2FocusLost(evt);
            }
        });

        jbLimpar1.setText("Limpar");
        jbLimpar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpar1ActionPerformed(evt);
            }
        });

        jLayeredPane3.setLayer(jbLimpar1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbLimpar1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addComponent(jbLimpar1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 82, Short.MAX_VALUE))
        );

        jtfCor2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfCor2FocusLost(evt);
            }
        });

        jtfEstadoCivil2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfEstadoCivil2FocusLost(evt);
            }
        });

        jtfSexo2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfSexo2FocusLost(evt);
            }
        });
        jtfSexo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfSexo2ActionPerformed(evt);
            }
        });

        jlTelefone2.setText("Telefone");

        jtfTelefone2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfTelefone2FocusLost(evt);
            }
        });

        jbCadastrar1.setText("Cadastrar");
        jbCadastrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addComponent(jbCadastrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLayeredPane3)
                        .addContainerGap())
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                                        .addComponent(jlNome2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtfNome2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jlCartao2))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jInternalFrame2Layout.createSequentialGroup()
                                        .addComponent(jlEstadoCivil2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jtfEstadoCivil2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jlSexo2)))
                                .addGap(18, 18, 18)
                                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfCartao2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfSexo2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                                        .addComponent(jlNumero1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtfNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addComponent(jlEndereco2))
                                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                                        .addComponent(jlCor2)
                                        .addGap(35, 35, 35)
                                        .addComponent(jtfCor2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfEndereco2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(jlRg2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jtfRg2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jlCep2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfCep2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jlCidade2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfCidade2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                                .addComponent(jlEstado2)
                                .addGap(18, 18, 18)
                                .addComponent(jtfEstado2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                                .addComponent(jlTelefone2)
                                .addGap(18, 18, 18)
                                .addComponent(jtfTelefone2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(23, 23, 23))))
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlNome2)
                            .addComponent(jlCartao2)
                            .addComponent(jtfNome2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfCartao2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlEstadoCivil2)
                            .addComponent(jlSexo2)
                            .addComponent(jtfEstadoCivil2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfSexo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfRg2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlRg2))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlEndereco2)
                            .addComponent(jtfEndereco2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame2Layout.createSequentialGroup()
                        .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfCor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlCor2))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlNumero1)
                            .addComponent(jtfNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame2Layout.createSequentialGroup()
                        .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlCep2)
                            .addComponent(jlCidade2)
                            .addComponent(jtfCep2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfCidade2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlEstado2)
                            .addComponent(jtfEstado2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlTelefone2)
                            .addComponent(jtfTelefone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCadastrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setText("Tipo (1 = Adm, 2 = Médico, 3 = Enfermeiro, 4 = Paciente):");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlEstado)
                                    .addComponent(jlCep))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(jtfCep, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jtfEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(94, 94, 94)
                                        .addComponent(jlCidade)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlTelefone)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfTpo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlCor)
                                .addGap(18, 18, 18)
                                .addComponent(jtfEtnia, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(79, 79, 79)
                                .addComponent(jlRg)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfRg, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlEndereco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jlNum)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jlCartao)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jlSexo)
                                    .addGap(18, 18, 18)
                                    .addComponent(jtfSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(51, 51, 51)
                                    .addComponent(jlEstadoCivil)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtSus, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(bntCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bntLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(170, 170, 170))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 401, Short.MAX_VALUE)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 400, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(223, 223, 223)
                    .addComponent(jLabel2)
                    .addContainerGap(578, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(233, 233, 233)
                    .addComponent(jLabel3)
                    .addContainerGap(568, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 401, Short.MAX_VALUE)
                    .addComponent(jInternalFrame2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 400, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNome)
                    .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCartao)
                    .addComponent(jtSus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSexo)
                    .addComponent(jtfSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlEstadoCivil)
                    .addComponent(jtfEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlCor)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfEtnia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlRg)
                        .addComponent(jtfRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlEndereco)
                    .addComponent(jtfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlNum)
                    .addComponent(jtfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlCep)
                    .addComponent(jtfCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlEstado)
                            .addComponent(jtfEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlCidade)
                            .addComponent(jtfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlTelefone)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(jtfTpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(166, 166, 166)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(166, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(176, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(156, 156, 156)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jInternalFrame2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfEstadoCivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfEstadoCivilActionPerformed
        if(jtfEstadoCivil.getText().isEmpty()){
            jtfEstadoCivil.setBackground(Color.red);
            
        }else{
            jtfEstadoCivil.setBackground(Color.white);
           
        }//fecha else
    }//GEN-LAST:event_jtfEstadoCivilActionPerformed

    private void jtfSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfSexoActionPerformed
         if(jtfSexo.getText().isEmpty()){
            jtfSexo.setBackground(Color.red);
            
        }else{
            jtfSexo.setBackground(Color.white);
           
        }//fecha else
    }//GEN-LAST:event_jtfSexoActionPerformed

    private void bntCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntCadastrarActionPerformed
        cadastrar();
        limpar();
    }//GEN-LAST:event_bntCadastrarActionPerformed

    private void bntLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntLimparActionPerformed
        limpar();
    }//GEN-LAST:event_bntLimparActionPerformed

    private void jtfNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNomeActionPerformed
         if(jtfNome.getText().isEmpty()){
            jtfNome.setBackground(Color.red);
            
        }else{
            jtfNome.setBackground(Color.white);
           
        }//fecha else
    }//GEN-LAST:event_jtfNomeActionPerformed

    private void jtSusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtSusActionPerformed
       if(jtSus.getText().isEmpty()){
            jtSus.setBackground(Color.red);
            
        }else{
            jtSus.setBackground(Color.white);
           
        }//fecha else
    }//GEN-LAST:event_jtSusActionPerformed

    private void jtfEtniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfEtniaActionPerformed
         if (jtfEtnia.getText().isEmpty()){
           jtfEtnia.setBackground(Color.red);
            
        }else{
           jtfEtnia.setBackground(Color.white);
           
        }//fecha else
    }//GEN-LAST:event_jtfEtniaActionPerformed

    private void jtfRgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfRgActionPerformed
        if(jtfRg.getText().isEmpty()){
            jtfRg.setBackground(Color.red);
            
        }else{
            jtfRg.setBackground(Color.white);
           
        }//fecha else
    }//GEN-LAST:event_jtfRgActionPerformed

    private void jtfNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNumeroActionPerformed
        if(jtfNumero.getText().isEmpty()){
            jtfNumero.setBackground(Color.red);
            
        }else{
            jtfNumero.setBackground(Color.white);
           
        }//fecha else
    }//GEN-LAST:event_jtfNumeroActionPerformed

    private void jtfEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfEnderecoActionPerformed
       if(jtfEndereco.getText().isEmpty()){
            jtfEndereco.setBackground(Color.red);
            
        }else{
            jtfEndereco.setBackground(Color.white);
           
        }//fecha else
    }//GEN-LAST:event_jtfEnderecoActionPerformed

    private void jtfCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCepActionPerformed
        if(jtfCep.getText().isEmpty()){
            jtfCep.setBackground(Color.red);
            
        }else{
            jtfCep.setBackground(Color.white);
           
        }//fecha else
    }//GEN-LAST:event_jtfCepActionPerformed

    private void jtfCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCidadeActionPerformed
        if(jtfCidade.getText().isEmpty()){
            jtfCidade.setBackground(Color.red);
            
        }else{
            jtfCidade.setBackground(Color.white);
           
        }//fecha else

    }//GEN-LAST:event_jtfCidadeActionPerformed

    private void jtfEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfEstadoActionPerformed
        if(jtfEstado.getText().isEmpty()){
            jtfEstado.setBackground(Color.red);
            
        }else{
            jtfEstado.setBackground(Color.white);
           
        }//fecha else
    }//GEN-LAST:event_jtfEstadoActionPerformed

    private void jtfTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfTelefoneActionPerformed
        if(jtfTelefone.getText().isEmpty()){
            jtfTelefone.setBackground(Color.red);
            
        }else{
            jtfTelefone.setBackground(Color.white);
           
        }//fecha else
    }//GEN-LAST:event_jtfTelefoneActionPerformed

    private void jtfNome1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfNome1FocusLost
        if(jtfNome.getText().isEmpty()){
            jtfNome.setBackground(Color.red);

        }else{
            jtfNome.setBackground(Color.white);

        }//fecha else

    }//GEN-LAST:event_jtfNome1FocusLost

    private void jtfNome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNome1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNome1ActionPerformed

    private void jtfCartao1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfCartao1FocusLost
        if(jtSus.getText().isEmpty()){
            jtSus.setBackground(Color.red);

        }else{
            jtSus.setBackground(Color.white);

        }//fecha else
    }//GEN-LAST:event_jtfCartao1FocusLost

    private void jtfRg1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfRg1FocusLost
        if(jtfRg.getText().isEmpty()){
            jtfRg.setBackground(Color.red);

        }else{
            jtfRg.setBackground(Color.white);

        }//fecha else
    }//GEN-LAST:event_jtfRg1FocusLost

    private void jtfEndereco1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfEndereco1FocusLost
        if(jtfEndereco.getText().isEmpty()){
            jtfEndereco.setBackground(Color.red);

        }else{
            jtfEndereco.setBackground(Color.white);

        }//fecha else
    }//GEN-LAST:event_jtfEndereco1FocusLost

    private void jtfNumero1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfNumero1FocusLost
        if(jtfNumero.getText().isEmpty()){
            jtfNumero.setBackground(Color.red);

        }else{
            jtfNumero.setBackground(Color.white);

        }//fecha else
    }//GEN-LAST:event_jtfNumero1FocusLost

    private void jtfCep1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfCep1FocusLost
        if(jtfCep.getText().isEmpty()){
            jtfCep.setBackground(Color.red);

        }else{
            jtfCep.setBackground(Color.white);

        }//fecha else
    }//GEN-LAST:event_jtfCep1FocusLost

    private void jtfCidade1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfCidade1FocusLost
        if(jtfCidade.getText().isEmpty()){
            jtfCidade.setBackground(Color.red);

        }else{
            jtfCidade.setBackground(Color.white);

        }//fecha else
    }//GEN-LAST:event_jtfCidade1FocusLost

    private void jtfEstado1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfEstado1FocusLost
        if(jtfEstado.getText().isEmpty()){
            jtfEstado.setBackground(Color.red);

        }else{
            jtfEstado.setBackground(Color.white);

        }//fecha else
    }//GEN-LAST:event_jtfEstado1FocusLost

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        limpar();
    }//GEN-LAST:event_jbLimparActionPerformed

    private void jtfCor1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfCor1FocusLost
        if (jtfEtnia.getText().isEmpty()){
           jtfEtnia.setBackground(Color.red);

        }else{
           jtfEtnia.setBackground(Color.white);

        }//fecha else
    }//GEN-LAST:event_jtfCor1FocusLost

    private void jtfEstadoCivil1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfEstadoCivil1FocusLost
        if(jtfEstadoCivil.getText().isEmpty()){
            jtfEstadoCivil.setBackground(Color.red);

        }else{
            jtfEstadoCivil.setBackground(Color.white);

        }//fecha else
    }//GEN-LAST:event_jtfEstadoCivil1FocusLost

    private void jtfSexo1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfSexo1FocusLost
        if(jtfSexo.getText().isEmpty()){
            jtfSexo.setBackground(Color.red);

        }else{
            jtfSexo.setBackground(Color.white);

        }//fecha else
    }//GEN-LAST:event_jtfSexo1FocusLost

    private void jtfSexo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfSexo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfSexo1ActionPerformed

    private void jtfTelefone1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfTelefone1FocusLost
        if(jtfTelefone.getText().isEmpty()){
            jtfTelefone.setBackground(Color.red);

        }else{
            jtfTelefone.setBackground(Color.white);

        }//fecha else
    }//GEN-LAST:event_jtfTelefone1FocusLost

    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        cadastrar();
        limpar();
    }//GEN-LAST:event_jbCadastrarActionPerformed

    private void jtfNome2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfNome2FocusLost
        if(jtfNome.getText().isEmpty()){
            jtfNome.setBackground(Color.red);

        }else{
            jtfNome.setBackground(Color.white);

        }//fecha else

    }//GEN-LAST:event_jtfNome2FocusLost

    private void jtfNome2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNome2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNome2ActionPerformed

    private void jtfCartao2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfCartao2FocusLost
        if(jtSus.getText().isEmpty()){
            jtSus.setBackground(Color.red);

        }else{
            jtSus.setBackground(Color.white);

        }//fecha else
    }//GEN-LAST:event_jtfCartao2FocusLost

    private void jtfRg2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfRg2FocusLost
        if(jtfRg.getText().isEmpty()){
            jtfRg.setBackground(Color.red);

        }else{
            jtfRg.setBackground(Color.white);

        }//fecha else
    }//GEN-LAST:event_jtfRg2FocusLost

    private void jtfEndereco2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfEndereco2FocusLost
        if(jtfEndereco.getText().isEmpty()){
            jtfEndereco.setBackground(Color.red);

        }else{
            jtfEndereco.setBackground(Color.white);

        }//fecha else
    }//GEN-LAST:event_jtfEndereco2FocusLost

    private void jtfNumero2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfNumero2FocusLost
        if(jtfNumero.getText().isEmpty()){
            jtfNumero.setBackground(Color.red);

        }else{
            jtfNumero.setBackground(Color.white);

        }//fecha else
    }//GEN-LAST:event_jtfNumero2FocusLost

    private void jtfCep2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfCep2FocusLost
        if(jtfCep.getText().isEmpty()){
            jtfCep.setBackground(Color.red);

        }else{
            jtfCep.setBackground(Color.white);

        }//fecha else
    }//GEN-LAST:event_jtfCep2FocusLost

    private void jtfCidade2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfCidade2FocusLost
        if(jtfCidade.getText().isEmpty()){
            jtfCidade.setBackground(Color.red);

        }else{
            jtfCidade.setBackground(Color.white);

        }//fecha else
    }//GEN-LAST:event_jtfCidade2FocusLost

    private void jtfEstado2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfEstado2FocusLost
        if(jtfEstado.getText().isEmpty()){
            jtfEstado.setBackground(Color.red);

        }else{
            jtfEstado.setBackground(Color.white);

        }//fecha else
    }//GEN-LAST:event_jtfEstado2FocusLost

    private void jbLimpar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpar1ActionPerformed
        limpar();
    }//GEN-LAST:event_jbLimpar1ActionPerformed

    private void jtfCor2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfCor2FocusLost
        if (jtfEtnia.getText().isEmpty()){
           jtfEtnia.setBackground(Color.red);

        }else{
           jtfEtnia.setBackground(Color.white);

        }//fecha else
    }//GEN-LAST:event_jtfCor2FocusLost

    private void jtfEstadoCivil2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfEstadoCivil2FocusLost
        if(jtfEstadoCivil.getText().isEmpty()){
            jtfEstadoCivil.setBackground(Color.red);

        }else{
            jtfEstadoCivil.setBackground(Color.white);

        }//fecha else
    }//GEN-LAST:event_jtfEstadoCivil2FocusLost

    private void jtfSexo2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfSexo2FocusLost
        if(jtfSexo.getText().isEmpty()){
            jtfSexo.setBackground(Color.red);

        }else{
            jtfSexo.setBackground(Color.white);

        }//fecha else
    }//GEN-LAST:event_jtfSexo2FocusLost

    private void jtfSexo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfSexo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfSexo2ActionPerformed

    private void jtfTelefone2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfTelefone2FocusLost
        if(jtfTelefone.getText().isEmpty()){
            jtfTelefone.setBackground(Color.red);

        }else{
            jtfTelefone.setBackground(Color.white);

        }//fecha else
    }//GEN-LAST:event_jtfTelefone2FocusLost

    private void jbCadastrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrar1ActionPerformed
        cadastrar();
        limpar();
    }//GEN-LAST:event_jbCadastrar1ActionPerformed
    
    private void cadastrar(){
        try {
            Pessoa p = new Pessoa();
            Adm a = new Adm();
            p.setNome(jtfNome.getText());
            p.setSus(jtSus.getText());
            p.setEtnia(jtfEtnia.getText());
            p.setSexo(jtfSexo.getText());
            p.setEstCivil(jtfEstadoCivil.getText());
            p.setRg(jtfRg.getText());
            p.setendereco(jtfEndereco.getText());
            p.setNum(jtfNumero.getText());
            p.setCep(jtfCep.getText());
            p.setCidade(jtfCidade.getText());
            p.setEstado(jtfEstado.getText());
            p.setTel(jtfTelefone.getText());
            p.settipo(Integer.parseInt(jtfTpo.getText()));
            
           
            
           
            a.cadastrarPessoa(p.getNome(), p.getSus(), p.getEstCivil(), p.getEtnia() , p.getSexo() , p.getRg(), p.getendereco(), p.getNum(), p.getCep() ,p.getCidade(), p.getEstado(), p.getTel(),p.gettipo());
            
            JOptionPane.showMessageDialog(
                    rootPane,
                    "Paciente cadastrado com sucesso!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                    "erro! " + e.getMessage());
        }
        
        
       
    }//fecha método cadastrar
    
     private void limpar() {
        jtfNome.setText("");
        jtSus.setText("");
        jtfEstadoCivil.setText("");
        jtfEtnia.setText("");
        jtfRg.setText("");
        jtfEndereco.setText("");
        jtfSexo.setText("");
        jtfNumero.setText("");
        jtfCidade.setText("");
        jtfCep.setText("");
        jtfEstado.setText("");
        jtfTelefone.setText("");
        jtfTpo.setText("");
                
    }//fecha método limpar
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntCadastrar;
    private javax.swing.JButton bntLimpar;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JButton jbCadastrar1;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JButton jbLimpar1;
    private javax.swing.JLabel jlCartao;
    private javax.swing.JLabel jlCartao1;
    private javax.swing.JLabel jlCartao2;
    private javax.swing.JLabel jlCep;
    private javax.swing.JLabel jlCep1;
    private javax.swing.JLabel jlCep2;
    private javax.swing.JLabel jlCidade;
    private javax.swing.JLabel jlCidade1;
    private javax.swing.JLabel jlCidade2;
    private javax.swing.JLabel jlCor;
    private javax.swing.JLabel jlCor1;
    private javax.swing.JLabel jlCor2;
    private javax.swing.JLabel jlEndereco;
    private javax.swing.JLabel jlEndereco1;
    private javax.swing.JLabel jlEndereco2;
    private javax.swing.JLabel jlEstado;
    private javax.swing.JLabel jlEstado1;
    private javax.swing.JLabel jlEstado2;
    private javax.swing.JLabel jlEstadoCivil;
    private javax.swing.JLabel jlEstadoCivil1;
    private javax.swing.JLabel jlEstadoCivil2;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlNome1;
    private javax.swing.JLabel jlNome2;
    private javax.swing.JLabel jlNum;
    private javax.swing.JLabel jlNumero;
    private javax.swing.JLabel jlNumero1;
    private javax.swing.JLabel jlRg;
    private javax.swing.JLabel jlRg1;
    private javax.swing.JLabel jlRg2;
    private javax.swing.JLabel jlSexo;
    private javax.swing.JLabel jlSexo1;
    private javax.swing.JLabel jlSexo2;
    private javax.swing.JLabel jlTelefone;
    private javax.swing.JLabel jlTelefone1;
    private javax.swing.JLabel jlTelefone2;
    private javax.swing.JTextField jtSus;
    private javax.swing.JTextField jtfCartao1;
    private javax.swing.JTextField jtfCartao2;
    private javax.swing.JTextField jtfCep;
    private javax.swing.JTextField jtfCep1;
    private javax.swing.JTextField jtfCep2;
    private javax.swing.JTextField jtfCidade;
    private javax.swing.JTextField jtfCidade1;
    private javax.swing.JTextField jtfCidade2;
    private javax.swing.JTextField jtfCor1;
    private javax.swing.JTextField jtfCor2;
    private javax.swing.JTextField jtfEndereco;
    private javax.swing.JTextField jtfEndereco1;
    private javax.swing.JTextField jtfEndereco2;
    private javax.swing.JTextField jtfEstado;
    private javax.swing.JTextField jtfEstado1;
    private javax.swing.JTextField jtfEstado2;
    private javax.swing.JTextField jtfEstadoCivil;
    private javax.swing.JTextField jtfEstadoCivil1;
    private javax.swing.JTextField jtfEstadoCivil2;
    private javax.swing.JTextField jtfEtnia;
    private javax.swing.JTextField jtfNome;
    private javax.swing.JTextField jtfNome1;
    private javax.swing.JTextField jtfNome2;
    private javax.swing.JTextField jtfNumero;
    private javax.swing.JTextField jtfNumero1;
    private javax.swing.JTextField jtfNumero2;
    private javax.swing.JTextField jtfRg;
    private javax.swing.JTextField jtfRg1;
    private javax.swing.JTextField jtfRg2;
    private javax.swing.JTextField jtfSexo;
    private javax.swing.JTextField jtfSexo1;
    private javax.swing.JTextField jtfSexo2;
    private javax.swing.JTextField jtfTelefone;
    private javax.swing.JTextField jtfTelefone1;
    private javax.swing.JTextField jtfTelefone2;
    private javax.swing.JTextField jtfTpo;
    // End of variables declaration//GEN-END:variables
}
