/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.ExameControle;
import controle.ProntuarioControle;
import java.awt.Color;
import java.io.FileWriter;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.Agenda;
import modelo.Prontuario;

/**
 *
 * @author laisp
 */
public class TelaCadProntuario extends javax.swing.JFrame {

    /**
     * Creates new form GUICadProntuario
     */
    public TelaCadProntuario() {
        initComponents();
        preencherConsulta();
        preencherPaciente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jlPaciente = new javax.swing.JLabel();
        jlMotivo = new javax.swing.JLabel();
        jbCadastrar = new javax.swing.JButton();
        jbApagar = new javax.swing.JButton();
        jcPaciente = new javax.swing.JComboBox<>();
        jcConsulta = new javax.swing.JComboBox<>();
        jlAno = new javax.swing.JLabel();
        jtfDia = new javax.swing.JTextField();
        jtfMes1 = new javax.swing.JTextField();
        jtfAno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtfHora = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtfMin = new javax.swing.JTextField();
        jlDia = new javax.swing.JLabel();
        jlMes = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel9.setText("jLabel9");

        jlPaciente.setText("Paciente:");

        jlMotivo.setText("Consulta:");

        jbCadastrar.setText("Cadastrar");
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });

        jbApagar.setText("Apagar");
        jbApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbApagarActionPerformed(evt);
            }
        });

        jlAno.setText("/");

        jtfDia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfDiaFocusLost(evt);
            }
        });
        jtfDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDiaActionPerformed(evt);
            }
        });

        jtfMes1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfMes1FocusLost(evt);
            }
        });

        jtfAno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfAnoFocusLost(evt);
            }
        });
        jtfAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfAnoActionPerformed(evt);
            }
        });

        jLabel5.setText("Hora:");

        jLabel6.setText(":");

        jlDia.setText("Data:");

        jlMes.setText("/");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlDia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfDia, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlMes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfMes1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlAno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfAno, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfHora, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfMin, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(42, 42, 42)
                            .addComponent(jbCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(146, 146, 146)
                            .addComponent(jbApagar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(19, 19, 19)
                                    .addComponent(jlPaciente))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jlMotivo)))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jcPaciente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jcConsulta, 0, 165, Short.MAX_VALUE)))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPaciente)
                    .addComponent(jcPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlMotivo)
                    .addComponent(jcConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDia)
                    .addComponent(jlMes)
                    .addComponent(jtfDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfMes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlAno)
                    .addComponent(jtfAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jtfMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jtfHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbApagar, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(jbCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        cadastrar();
        limpar();
    }//GEN-LAST:event_jbCadastrarActionPerformed

    private void jbApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbApagarActionPerformed
        limpar();
    }//GEN-LAST:event_jbApagarActionPerformed

    private void jtfDiaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfDiaFocusLost
        if(jtfDia.getText().isEmpty()){
            jtfDia.setBackground(Color.red);

        }else{
            jtfDia.setBackground(Color.white);

        }//fecha else
    }//GEN-LAST:event_jtfDiaFocusLost

    private void jtfDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDiaActionPerformed

    private void jtfMes1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfMes1FocusLost
        if(jtfMes.getText().isEmpty()){
            jtfMes.setBackground(Color.red);

        }else{
            jtfMes.setBackground(Color.white);

        }//fecha else
    }//GEN-LAST:event_jtfMes1FocusLost

    private void jtfAnoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfAnoFocusLost
        if(jtfAno.getText().isEmpty()){
            jtfAno.setBackground(Color.red);

        }else{
            jtfAno.setBackground(Color.white);

        }//fecha else
    }//GEN-LAST:event_jtfAnoFocusLost

    private void jtfAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfAnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfAnoActionPerformed

     private void preencherConsulta(){
        try {
            ProntuarioControle p = new ProntuarioControle();
            ArrayList<String> tp = new ArrayList();
            tp = p.preencherConsulta();
            
            for (int i = 0; i <tp.size(); i++){
                jcConsulta.addItem(tp.get(i));
            }
       } catch (Exception e) {
            JOptionPane.showMessageDialog(
                this, "Erro! " + e.getMessage());
        }
    }
    
    public void preencherPaciente(){
        try {
            ProntuarioControle p = new ProntuarioControle();
            ArrayList<String> tp = new ArrayList();
            tp = p.preencherPaciente();
            
            for (int i = 0; i <tp.size(); i++){
                jcPaciente.addItem(tp.get(i));
            }
       } catch (Exception e) {
            JOptionPane.showMessageDialog(
                this, "Erro! " + e.getMessage());
        }
    }
    
     private void cadastrar() {
        try {
            Prontuario p  = new Prontuario();
            ProntuarioControle pc = new ProntuarioControle();
            p.setIdpaciente(pc.procurarIdPaciente(jcPaciente.getSelectedItem().toString()));
            p.setConsultatipo(pc.procurarId(jcConsulta.getSelectedItem().toString()));
            p.setAno(jtfAno.getText());
            p.setMes(jtfMes.getText());
            p.setDia(jtfDia.getText());
            p.sethora(jtfHora.getText());
            p.setmin(jtfMin.getText());
            
            
            
            
            pc.alterarProntuario(p.getIdpaciente(), p.getAno(), p.getMes(), p.getDia(), p.gethora(), p.getmin(), p.getConsultatipo());
            
            JOptionPane.showMessageDialog(
                    rootPane,
                    "Produto cadastrado com sucesso!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                    "erro! " + e.getMessage());
        }//fecha catch
        
    }//fecha método cadastrar
    
    private void limpar() {
        jtfAno.setText("");
        jtfMes.setText("");
        jtfDia.setText("");
        jtfHora.setText("");
        jtfMin.setText("");
                
    }//fecha método limpar
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadProntuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadProntuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadProntuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadProntuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadProntuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton jbApagar;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JComboBox<String> jcConsulta;
    private javax.swing.JComboBox<String> jcPaciente;
    private javax.swing.JLabel jlAno;
    private javax.swing.JLabel jlDia;
    private javax.swing.JLabel jlMes;
    private javax.swing.JLabel jlMotivo;
    private javax.swing.JLabel jlPaciente;
    private javax.swing.JTextField jtfAno;
    private javax.swing.JTextField jtfDia;
    private javax.swing.JTextField jtfHora;
    private javax.swing.JTextField jtfMes;
    private javax.swing.JTextField jtfMes1;
    private javax.swing.JTextField jtfMin;
    // End of variables declaration//GEN-END:variables
}
