/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.ExameControle;
import java.awt.Color;
import java.sql.Array;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Agenda;
import modelo.Exame;
import modelo.Tipo_Exame;

/**
 *
 * @author laisp
 */
public class TelaTabExame extends javax.swing.JFrame {

    DefaultTableModel dtm = new DefaultTableModel(
            new Object[][]{},
            new Object[]{"id_exame", "Paciente", "Data e Hora", "Exame"});
    
    public TelaTabExame() {
        initComponents();
        preencherTabela();
        preecherExame();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfPaciente = new javax.swing.JTextField();
        jtfCodigo = new javax.swing.JTextField();
        jbAlterar = new javax.swing.JButton();
        jbConfirmar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtDados = new javax.swing.JTable();
        jbAtualizar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jlData = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtfHora = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtfMin = new javax.swing.JTextField();
        jlDia = new javax.swing.JLabel();
        jlMes = new javax.swing.JLabel();
        jlAno = new javax.swing.JLabel();
        jtfDia = new javax.swing.JTextField();
        jtfMes = new javax.swing.JTextField();
        jtfAno = new javax.swing.JTextField();
        jcExame = new javax.swing.JComboBox<>();

        jLabel2.setText("Codigo");

        jLabel3.setText("Paciente:");

        jtfPaciente.setEditable(false);
        jtfPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfPacienteActionPerformed(evt);
            }
        });

        jtfCodigo.setEditable(false);
        jtfCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCodigoActionPerformed(evt);
            }
        });

        jbAlterar.setText("Alterar");
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });

        jbConfirmar.setText("Confirmar");
        jbConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConfirmarActionPerformed(evt);
            }
        });

        jtDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Paciente", "Data e Hora", "Exame"
            }
        ));
        jScrollPane1.setViewportView(jtDados);

        jbAtualizar.setText("Atualizar");
        jbAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAtualizarActionPerformed(evt);
            }
        });

        jLabel4.setText("Exame:");

        jlData.setText("Data");

        jLabel5.setText("Hora:");

        jLabel6.setText(":");

        jlDia.setText("Data:");

        jlMes.setText("/");

        jlAno.setText("/");

        jtfDia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfDiaFocusLost(evt);
            }
        });
        jtfDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDiaActionPerformed(evt);
            }
        });

        jtfMes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfMesFocusLost(evt);
            }
        });

        jtfAno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfAnoFocusLost(evt);
            }
        });
        jtfAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfAnoActionPerformed(evt);
            }
        });

        jcExame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcExameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcExame, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jbAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jtfPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlDia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfDia, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlMes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfMes, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlData)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlAno)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfAno, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfHora, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfMin, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jtfPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jcExame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jlData, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDia)
                    .addComponent(jlMes)
                    .addComponent(jtfDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlAno)
                    .addComponent(jtfAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jtfMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jtfHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed
       alterar();
    }//GEN-LAST:event_jbAlterarActionPerformed

    private void jbConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConfirmarActionPerformed
       confirmarAlteracao();
        limparTabela();
        limparCampos();
        preencherTabela();
    }//GEN-LAST:event_jbConfirmarActionPerformed

    private void jbAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAtualizarActionPerformed
        limparTabela();
        preencherTabela();
    }//GEN-LAST:event_jbAtualizarActionPerformed

    private void jtfCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCodigoActionPerformed
        if(jtfCodigo.getText().isEmpty()){
            jtfCodigo.setBackground(Color.red);
            
        }else{
            jtfCodigo.setBackground(Color.white);
           
        }//fecha else
    }//GEN-LAST:event_jtfCodigoActionPerformed

    private void jtfPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPacienteActionPerformed
         if(jtfPaciente.getText().isEmpty()){
            jtfPaciente.setBackground(Color.red);
            
        }else{
            jtfPaciente.setBackground(Color.white);
           
        }//fecha else
    }//GEN-LAST:event_jtfPacienteActionPerformed

    private void jtfDiaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfDiaFocusLost
        if(jtfDia.getText().isEmpty()){
            jtfDia.setBackground(Color.red);

        }else{
            jtfDia.setBackground(Color.white);

        }//fecha else
    }//GEN-LAST:event_jtfDiaFocusLost

    private void jtfDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDiaActionPerformed

    private void jtfMesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfMesFocusLost
        if(jtfMes.getText().isEmpty()){
            jtfMes.setBackground(Color.red);

        }else{
            jtfMes.setBackground(Color.white);

        }//fecha else
    }//GEN-LAST:event_jtfMesFocusLost

    private void jtfAnoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfAnoFocusLost
        if(jtfAno.getText().isEmpty()){
            jtfAno.setBackground(Color.red);

        }else{
            jtfAno.setBackground(Color.white);

        }//fecha else
    }//GEN-LAST:event_jtfAnoFocusLost

    private void jtfAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfAnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfAnoActionPerformed

    private void jcExameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcExameActionPerformed
        
    }//GEN-LAST:event_jcExameActionPerformed

    private void preecherExame(){
        try {
            ExameControle ec = new ExameControle();
            
            ArrayList<String> te = new ArrayList();
            
            te = ec.preencherExame();
            
            for (int i = 0; i <te.size(); i++){
                jcExame.addItem(te.get(i));
            }//fecha for
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                this, "Erro! " + e.getMessage());
        }
    }
    
  
    
     private void preencherTabela() {
        try {

            ExameControle p = new ExameControle();

            ArrayList<Exame> e = new ArrayList<>();

            e = p.preencherTabela();
            dtm.setNumRows(0);
            for (int i = 0; i <e.size(); i++) {
                dtm.addRow(new Object[]{
                    String.valueOf(e.get(i).getIdExame()),
                    String.valueOf(e.get(i).getpaciente()),
                    String.valueOf(e.get(i).juntarDataTabela()),
                    String.valueOf(e.get(i).getexame())
                     
            });
            }//fecha for

            /* Adicionando o modelo de tabela 
             com os dados na tabela produto */
            jtDados.setModel(dtm);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Erro! " + e.getMessage());
        }//fecha catch
    }//fecha preencherTabela
    
    private void alterar() {
        Exame e = new Exame();
        int linha = jtDados.getSelectedRow();
            if(linha != -1) {
            jtfCodigo.setText((String)jtDados.getValueAt(linha, 0));
            jtfPaciente.setText((String)jtDados.getValueAt(linha, 1));
            e.Data((String)jtDados.getValueAt(linha, 2));
            jtfDia.setText(e.getDia());
            jtfMes.setText(e.getMes());
            jtfAno.setText(e.getAno());
            jtfHora.setText(e.gethora());
            jtfMin.setText(e.getmin());
            
          
            }else{
                JOptionPane.showMessageDialog(this, 
                        "Você não selecionou nenhuma linha!");
         }//fecha else
    }//fecha método
    
     private void limparTabela() {
      /* Para limpar a tabela temos que setar o número de
           linhas para zero no default table model */        
        dtm.setNumRows(0);
    }//fecha limparTabela
    
    private void limparCampos(){
        jtfCodigo.setText("");
        jtfPaciente.setText("");
        jtfDia.setText("");
        jtfMes.setText("");
        jtfAno.setText("");
        jtfHora.setText("");
        jtfMin.setText("");
        
    }
    
     private void confirmarAlteracao(){
        try {
            Exame e = new Exame();
            ExameControle ec = new ExameControle();
            
            e.setIdExame(Integer.parseInt(jtfCodigo.getText()));
            e.setExametipo(ec.procurarId(jcExame.getSelectedItem().toString()));
            e.setAno(jtfAno.getText());
            e.setMes(jtfMes.getText());
            e.setDia(jtfDia.getText());
            e.sethora(jtfHora.getText());
            e.setmin(jtfMin.getText());
            
            ec.alterarExame(e.getIdExame(), e.getAno(), e.getMes(), e.getDia(), e.gethora(), e.getmin(),e.getExametipo());
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                    "erro! " + e.getMessage());
        }
    }
     
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaTabExame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaTabExame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaTabExame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaTabExame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaTabExame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbAtualizar;
    private javax.swing.JButton jbConfirmar;
    private javax.swing.JComboBox<String> jcExame;
    private javax.swing.JLabel jlAno;
    private javax.swing.JLabel jlData;
    private javax.swing.JLabel jlDia;
    private javax.swing.JLabel jlMes;
    private javax.swing.JTable jtDados;
    private javax.swing.JTextField jtfAno;
    private javax.swing.JTextField jtfCodigo;
    private javax.swing.JTextField jtfDia;
    private javax.swing.JTextField jtfHora;
    private javax.swing.JTextField jtfMes;
    private javax.swing.JTextField jtfMin;
    private javax.swing.JTextField jtfPaciente;
    // End of variables declaration//GEN-END:variables
}
